apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: QWxleE9vcHM6Z2l0aHViX3BhdF8xMUFSNUI0WEEwNEVDR3hmdmRSek9iX0FTTDVTa3FZQWlzNXNVZzB1TDZNUUVVb3AzenJCUlBDakJsQ2xhTk5BZkdEMk5GUFVVRllNTnBnNDhw
